var videoSrt = [
  {
    id: 1,
    startTime: 3000,
    endTime: 5669,
    diference: 2669,
    text: 'Oh, shit. Oh, shit. Oh, shit.',
    translate: 'Ah Merda. Ah Merda. Ah Merda.',
  },
  {
    id: 2,
    startTime: 6170,
    endTime: 8172,
    diference: 2002,
    text: "\nThat one's moving away from us.",
    translate: ' nEsse está se afastando de nós.',
  },
  {
    id: 3,
    startTime: 14678,
    endTime: 16347,
    diference: 1669,
    text: '\nWe need the recorder.',
    translate: ' nPrecisamos do gravador.',
  },
  {
    id: 4,
    startTime: 26524,
    endTime: 28776,
    diference: 2252,
    text: ' Brand, Doyle, back to the Ranger now!',
    translate: '  Brand, Doyle, de volta ao Ranger agora!',
  },
  {
    id: 5,
    startTime: 28943,
    endTime: 32321,
    diference: 3378,
    text: "We're not leaving without her data.",
    translate: 'Não vamos embora sem os dados dela.',
  },
  {
    id: 6,
    startTime: 32488,
    endTime: 33823,
    diference: 1335,
    text: 'Get back here now!',
    translate: 'Volte aqui agora!',
  },
  {
    id: 7,
    startTime: 33989,
    endTime: 35699,
    diference: 1710,
    text: 'We do not have time!',
    translate: 'Não temos tempo!',
  },
  {
    id: 8,
    startTime: 35866,
    endTime: 38327,
    diference: 2461,
    text: "The second wave is coming!\nWe're in the middle of a swell.",
    translate: 'A segunda onda está chegando!  NEstamos no meio de um swell.',
  },
  {
    id: 9,
    startTime: 39620,
    endTime: 41038,
    diference: 1418,
    text: '\nNo, I got it.',
    translate: ' nNão, entendi.',
  },
  {
    id: 10,
    startTime: 41205,
    endTime: 43207,
    diference: 2002,
    text: 'Get your ass back to the Ranger now!',
    translate: 'Volte para o Ranger agora!',
  },
  {
    id: 11,
    startTime: 44041,
    endTime: 45376,
    diference: 1335,
    text: '',
    translate: '',
  },
  {
    id: 12,
    startTime: 48212,
    endTime: 50256,
    diference: 2044,
    text: 'Brand, get back here now!',
    translate: 'Brand, volte aqui agora!',
  },
  {
    id: 13,
    startTime: 52216,
    endTime: 54426,
    diference: 2210,
    text: "\nNo, Cooper, go. Cooper, go. I can't make it.",
    translate: ' nNão, Cooper, vá. Cooper, vá. Eu não posso fazer isso.',
  },
  {
    id: 14,
    startTime: 54844,
    endTime: 57221,
    diference: 2377,
    text: '- Go!\n- CASE, go get her.',
    translate: '- Vá!  N- CASE, vá buscá-la.',
  },
  {
    id: 15,
    startTime: 62017,
    endTime: 64019,
    diference: 2002,
    text: '- Go!\n- Get up. Get up, Brand!',
    translate: '- Vá!  N- Levante-se. Levante-se, Brand!',
  },
  {
    id: 16,
    startTime: 64937,
    endTime: 66438,
    diference: 1501,
    text: '\nGo, go! Go!',
    translate: ' nVá, vá! Ir!',
  },
  {
    id: 17,
    startTime: 68023,
    endTime: 70860,
    diference: 2837,
    text: "- I'm not gonna make it!\n- Yes, you are. Yes, you are!",
    translate: '- Eu não vou conseguir!  N- Sim, você vai. Sim você é!',
  },
  {
    id: 18,
    startTime: 77700,
    endTime: 79994,
    diference: 2294,
    text: 'Come on, CASE has her!\nGet back here, Doyle!',
    translate: 'Vamos, CASE está com ela!  NVolte aqui, Doyle!',
  },
]
