const songs = [
  {
    song_Name: 'default',
    reels: 0000,
    id: 0000,
    emAlta: false,
    problem: false,
    done: false,
    link: 'link',
  },
  {
    song_Name: 'what about us',
    reels: 0000,
    id: 2924936,
    emAlta: false,
    problem: false,
    done: true,
    link: 'https://www.letras.mus.br/pink/what-about-us/',
  },
  {
    song_Name: 'Un-Break My Heart',
    reels: 0000,
    id: 5736,
    emAlta: false,
    problem: false,
    done: true,
    link: 'https://www.letras.mus.br/toni-braxton/5736/',
  },
  {
    song_Name: 'Can't Hold Us',
    reels: 0000,
    id: 2495790,
    emAlta: false,
    problem: false,
    done: true,
    link: 'https://www.letras.mus.br/macklemore/cant-hold-us/',
  },
  {
    song_Name: 'Payphone',
    reels: 0000,
    id: 2098035,
    emAlta: false,
    problem: false,
    done: true,
    link: 'https://www.letras.mus.br/maroon-5/payphone-ft-wiz-khalifa/',
  },
  {
    song_Name: 'goosebumps',
    reels: 0000,
    id: 2843321,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/travis-scott/goosebumps/',
  },
  {
    song_Name: 'Money',
    reels: 0000,
    id: 63079,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/pink-floyd/63079/',
  },
  {
    song_Name: 'sicko mode',
    reels: 0000,
    id: 3033296,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/travis-scott/sicko-mode/',
  },
  {
    song_Name: 'highest in the room',
    reels: 0000,
    id: 3213230,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/travis-scott/highest-in-the-room/',
  },
  {
    song_Name: 'Kangaroo Court',
    reels: 0000,
    id: 2546781,
    problem: true,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/capital-cities/kangaroo-court/',
  },
  {
    song_Name: 'Without You',
    reels: 250,
    id: 6869,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/mariah-carey/6869/',
  },
  {
    song_Name: 'Pompeii',
    reels: 0000,
    id: 2188897,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/bastille/pompeii/',
  },
  {
    song_Name: 'The Final Countdown',
    reels: 0000,
    id: 13191,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/europe/13191/',
  },
  {
    song_Name: 'Stereo Hearts',
    reels: 0000,
    id: 1905877,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/gym-class-heroes/1905877/',
  },
  {
    song_Name: 'Love Me Again',
    reels: 0000,
    id: 2531347,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/john-newman/love-me-again/',
  },
  {
    song_Name: 'Nothing Breaks Like a Heart',
    reels: 0000,
    id: 3084187,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/miley-cyrus/nothing-breaks-like-a-heart-feat-mark-ronson/',
  },
  {
    song_Name: 'Girl On Fire',
    reels: 0000,
    id: 2167337,
    emAlta: true,
    problem: true,
    done: false,
    link: 'https://www.letras.mus.br/alicia-keys/girl-on-fire-1/',
  },
  {
    song_Name: 'All Star',
    reels: 0000,
    id: 36129,
    emAlta: false,
    problem: true,
    done: false,
    link: 'https://www.letras.mus.br/smash-mouth/36129/',
  },
  {
    song_Name: 'I Hate Everything About You',
    reels: 0000,
    id: 74182,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/three-days-grace/74182/',
  },
  {
    song_Name: 'As Long As You Love Me',
    reels: 0000,
    id: 2772,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/backstreet-boys/2772/',
  },
  {
    song_Name: "Don't Speak",
    reels: 0000,
    id: 84746,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/no-doubt/84746/',
  },
  {
    song_Name: 'The One That Got Away',
    reels: 0000,
    id: 1725495,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/katy-perry/1725495/',
  },
  {
    song_Name: 'Last Friday Night (T.G.I.F.)',
    reels: 0000,
    id: 1725490,
    emAlta: false,
    problem: true,
    done: false,
    link: 'https://www.letras.mus.br/katy-perry/1725490/',
  },
  {
    song_Name: 'The Good Part',
    reels: 0000,
    id: 2918908,
    emAlta: true,
    problem: true,
    done: false,
    link: 'https://www.letras.mus.br/ajr/the-good-part/',
  },
  {
    song_Name: 'Before You Go',
    reels: 0000,
    id: 3234730,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/lewis-capaldi/before-you-go/',
  },
  {
    song_Name: 'Vella (cover) I See Red',
    reels: 0000,
    id: 3271077,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/everybody-loves-an-outlaw/i-see-red/',
  },
  {
    song_Name: 'I Took a Pill In Ibiza',
    reels: 0000,
    id: 2726491,
    emAlta: true,
    problem: true,
    done: true,
    link: 'https://www.letras.mus.br/mike-posner/i-took-a-pill-in-ibiza/',
  },
  {
    song_Name: 'Jealous',
    reels: 0000,
    id: 2683176,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/labrinth/jealous/',
  },
  {
    song_Name: 'Tell Me You Love Me',
    reels: 0000,
    id: 2928149,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/demi-lovato/tell-me-you-love-me/',
  },
  {
    song_Name: 'Closer ',
    reels: 1200,
    id: 2818761,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/lemaitre/closer/',
  },
  {
    song_Name: 'Live And Let Die',
    reels: 593,
    id: 17099,
    problem: true,
    emAlta: false,
    link: 'https://www.letras.mus.br/guns-n-roses/17099/traducao.html',
  },
  {
    song_Name: 'Boss Bitch',
    reels: 0000,
    id: 3259754,
    problem: true,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/doja-cat/boss-bitch/',
  },
  {
    song_Name:
      'Sweet Dreams (Are Made Of This) (feat. Annie Lennox & Dave Stewart)',
    reels: 28700,
    id: 13225,
    emAlta: true,
    problem: true,
    link: 'https://www.letras.mus.br/eurythmics/13225/',
  },
  {
    song_Name: 'Lonely',
    reels: 20700,
    id: 98337,
    emAlta: true,
    done: false,
    problem: true,
    link: 'https://www.letras.mus.br/akon/98337/',
  },
  {
    song_Name: "Don't You Worry Child (feat. John Martin)",
    reels: 16900,
    id: 2142555,
    emAlta: true,
    done: false,
    problem: true,
    link: 'https://www.letras.mus.br/swedish-house-mafia/dont-you-worry-child/',
  },

  {
    song_Name: 'I Gotta Feeling',
    reels: 0000,
    id: 1487982,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/black-eyed-peas/1487982/',
  },
  {
    song_Name: 'EARFQUAKE',
    reels: 2703,
    id: 3149164,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/tyler-the-creator/earfquake/',
  },
  {
    song_Name: 'Dance Monkey',
    reels: 0000,
    id: 3182507,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/tones-and-i/dance-monkey/',
  },
  {
    song_Name: 'If I Were a Boy',
    reels: 0000,
    id: 1443820,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/beyonce/1443820/',
  },
  {
    song_Name: 'No Lie',
    reels: 0000,
    id: 2858268,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/sean-paul/no-lie/',
  },
  {
    song_Name: 'Circles',
    reels: 0000,
    id: 3187752,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/post-malone/circles/',
  },
  {
    song_Name: 'Worth It',
    reels: 0000,
    id: 2699839,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/fifth-harmony/worth-it/',
  },
  {
    song_Name: 'Rise Up',
    reels: 0000,
    id: 2779720,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/andra-day/rise-up/',
  },
  {
    song_Name: 'Fix You',
    reels: 0000,
    id: 183253,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/coldplay/183253/',
  },
  {
    song_Name: 'Billionaire',
    reels: 0000,
    id: 1666857,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/travie-mccoy/1666857/',
  },
  {
    song_Name: 'Under Pressure',
    reels: 0000,
    id: 64294,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/queen/64294/',
  },
  {
    song_Name: 'Bills, Bills, Bills',
    reels: 0000,
    id: 10562,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/destinys-child/10562/',
  },
  {
    song_Name: 'All I Want For Christmas Is You',
    reels: 0000,
    id: 6892,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/mariah-carey/6892/',
  },
  {
    song_Name: 'MONEY',
    reels: 0000,
    id: 3530613,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/lisa-blackpink/money/',
  },
  {
    song_Name: 'Human',
    reels: 0000,
    id: 2830078,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ragnbone-man/human/',
  },
  {
    song_Name: '6th Avenue Heartache',
    reels: 86,
    id: 89236,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/the-wallflowers/89236/',
  },
  {
    song_Name: 'dont go yet',
    reels: 29500,
    id: 3509972,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/camila-cabello/dont-go-yet/',
  },
  {
    song_Name: 'Stay',
    reels: 0000,
    id: 3504384,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/justin-bieber/stay-feat-the-kid-laroi/',
  },
  {
    song_Name: 'traitor',
    reels: 0000,
    id: 3483330,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/olivia-rodrigo/traitor/',
  },
  {
    song_Name: 'Venom',
    reels: 0000,
    id: 3041658,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/eminem/venom/',
  },
  {
    song_Name: 'In Da Club',
    reels: 0000,
    id: 67581,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/50-cent/67581/',
  },
  {
    song_Name: "Gangsta's Paradise",
    reels: 0000,
    id: 8361,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/coolio/8361/',
  },

  {
    song_Name: 'Gangsta',
    reels: 0000,
    id: 0000,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/kehlani/gangsta/',
  },
  {
    song_Name: 'The Search',
    reels: 0000,
    id: 3155090,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/nf/the-search/',
  },
  {
    song_Name: 'Levitating',
    reels: 0000,
    id: 3287901,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/dua-lipa/levitating/',
  },
  {
    song_Name: 'Highway To Hell',
    reels: 0000,
    id: 615,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ac-dc/615/',
  },
  {
    song_Name: 'Cough Syrup',
    reels: 0000,
    id: 1618242,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/young-the-giant/1618242/',
  },
  {
    song_Name: 'Somebody That I Used To Know',
    reels: 0000,
    id: 1922385,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/gotye/1922385/',
  },
  {
    song_Name: 'It Must Have Been Love',
    reels: 0000,
    id: 34458,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/roxette/34458/',
  },
  {
    song_Name: 'Male Fantasy',
    reels: 0000,
    id: 3512932,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/billie-eilish/male-fantasy/',
  },
  {
    song_Name: 'I Will Always Love You',
    reels: 0000,
    id: 18488,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/whitney-houston/18488/',
  },
  {
    song_Name: 'numb',
    reels: 0000,
    id: 429206,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/linkin-park/429206/',
  },
  {
    song_Name: 'More Than Words',
    reels: 0000,
    id: 3417,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/extreme/3417/',
  },
  {
    song_Name: "It's My Life",
    reels: 83200,
    id: 4924,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/bon-jovi/4924/',
  },
  {
    song_Name: 'Hey Ya!',
    reels: 38200,
    id: 77513,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/outkast/77513/',
  },
  {
    song_Name: 'Creep',
    reels: 0000,
    id: 63485,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/radiohead/63485/',
  },
  {
    song_Name: 'mood',
    reels: 0000,
    id: 3359149,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/24kgoldn/mood-feat-iann-dior/',
  },
  {
    song_Name: "What's Up?",
    reels: 0000,
    id: 1129164,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/4-non-blondes/1129164/',
  },
  {
    song_Name: 'Take Me To Church',
    reels: 0000,
    id: 2611955,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/hozier/take-me-to-church/',
  },
  {
    song_Name: 'Stone Cold',
    reels: 0000,
    id: 2766150,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/demi-lovato/stone-cold/',
  },
  {
    song_Name: 'Happiest Year',
    reels: 0000,
    id: 3176999,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/james-young/happiest-year/',
  },
  {
    song_Name: 'Hey Jude',
    reels: 0000,
    id: 88,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/the-beatles/88/',
  },
  {
    song_Name: 'Happier Than Ever',
    reels: 0000,
    id: 3512935,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/billie-eilish/happier-than-ever/',
  },
  {
    song_Name: 'Just The Way You Are',
    reels: 0000,
    id: 1715605,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/bruno-mars/1715605/',
  },
  {
    song_Name: "I'm Yours",
    reels: 0000,
    id: 1408813,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/jason-mraz/1408813/',
  },
  {
    song_Name: 'Break My Heart',
    reels: 109000,
    id: 3265447,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/dua-lipa/break-my-heart/',
  },
  {
    song_Name: "Don't Start Now",
    reels: 252000,
    id: 3225733,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/dua-lipa/dont-start-now/',
  },
  {
    song_Name: 'Hymn For The Weekend',
    reels: 0000,
    id: 2775113,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/coldplay/hymn-for-the-weekend/',
  },
  {
    song_Name: 'Halo',
    reels: 0000,
    id: 1368417,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/beyonce/1368417/',
  },
  {
    song_Name: 'What Makes You Beautiful',
    reels: 0000,
    id: 0000,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/one-direction/1947050/',
  },
  {
    song_Name: 'Sign Of The Times',
    reels: 0000,
    id: 2891613,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/harry-styles/sign-of-the-times/',
  },
  {
    song_Name: 'Watermelon Sugar',
    reels: 0000,
    id: 3232450,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/harry-styles/watermelon-sugar/',
  },
  {
    song_Name: 'Say My Name',
    reels: 0000,
    id: 3047329,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/david-guetta/say-my-name-feat-bebe-rexha-e-j-balvin/',
  },
  {
    song_Name: 'Say So',
    reels: 95900,
    id: 3229334,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/doja-cat/say-so/',
  },
  {
    song_Name: 'If The World Was Ending',
    reels: 0000,
    id: 3219931,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/jp-saxe/if-the-world-was-ending-feat-julia-michael/',
  },
  {
    song_Name: 'My Life Is Going On',
    reels: 0000,
    id: 0000,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/cecilia-krull/my-life-is-going-on/',
  },
  {
    song_Name: 'Dollhouse',
    reels: 0000,
    id: 3498161,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/melanie-martinez/dollhouse/',
  },
  {
    song_Name: 'Bad Habits',
    reels: 0000,
    id: 3498161,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ed-sheeran/bad-habits/',
  },
  {
    song_Name: 'Heather',
    reels: 23500,
    id: 3284358,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/conan-gray/heather/',
  },
  {
    song_Name: 'idontwannabeyouanymore',
    reels: 11000,
    id: 2920410,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/billie-eilish/idontwannabeyouanymore/',
  },
  {
    song_Name: 'High Enough',
    reels: 9771,
    id: 2894113,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/kflay/high-enough/',
  },
  {
    song_Name: 'pity party',
    reels: 2021,
    id: 2738050,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/melanie-martinez/pity-party/',
  },
  {
    song_Name: 'Am I Wrong',
    reels: 55000,
    id: 2615769,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/nico-e-vinz/am-i-wrong/',
  },
  {
    song_Name: 'Who You Are',
    reels: 5701,
    id: 1776129,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/jessie-j/1776129/',
  },
  {
    song_Name: 'Boogie Wonderland',
    reels: 5666,
    id: 12023,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/earth-wind-and-fire/12023/',
  },
  {
    song_Name: 'Price Tag',
    reels: 5884,
    id: 1777864,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/jessie-j/1777864/',
  },
  {
    song_Name: 'What Is Love?',
    reels: 0000,
    id: 996845,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/haddaway/996845/',
  },
  {
    song_Name: 'Boulevard of Broken Dreams',
    reels: 5299,
    id: 101227,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/green-day/101227/',
  },
  {
    song_Name: 'Counting Stars',
    reels: 30100,
    id: 2213982,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/one-republic/counting-stars/',
  },
  {
    song_Name: 'Cheap Thrills',
    reels: 79900,
    id: 2778209,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/sia/cheap-thrills/',
  },
  {
    song_Name: 'Snowman',
    reels: 3000,
    id: 2951105,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/sia/snowman/',
  },
  {
    song_Name: 'Need You Now',
    reels: 1245,
    id: 1539868,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/lady-antebellum/1539868/',
  },
  {
    song_Name: 'Fancy (feat. Charli XCX)',
    reels: 9577,
    id: 2609770,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/iggy-azalea/fancy/',
  },
  {
    song_Name: 'Conversations In The Dark',
    reels: 2857,
    id: 3254346,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/john-legend/conversations-in-the-dark/',
  },
  {
    song_Name: 'All Of Me',
    reels: 51900,
    id: 2524763,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/john-legend/all-of-me/',
  },
  {
    song_Name: 'The best',
    reels: 0000,
    id: 298665,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/tina-turner/298665/',
  },
  {
    song_Name: 'Firework',
    reels: 0000,
    id: 1731882,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/katy-perry/1731882/',
  },
  {
    song_Name: 'In The End',
    reels: 0000,
    id: 23091,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/linkin-park/23091/',
  },
  {
    song_Name: 'Stop Crying Your Heart Out',
    reels: 0000,
    id: 63270,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/oasis/63270/',
  },
  {
    song_Name: "Don't Look Back In Anger",
    reels: 0000,
    id: 28994,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/oasis/28994/',
  },
  {
    song_Name: 'Kings & Queens',
    reels: 0000,
    id: 3281453,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ava-max/kings-e-queens/',
  },
  {
    song_Name: 'Sweet But Psycho',
    reels: 15200,
    id: 3052271,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ava-max/sweet-but-psycho/',
  },
  {
    song_Name: 'Story of my life',
    reels: 14300,
    id: 2575306,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/one-direction/story-of-my-life/',
  },
  {
    song_Name: 'Chasing Cars',
    reels: 5656,
    id: 536400,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/snow-patrol/536400/',
  },
  {
    song_Name: "say you won't let go",
    reels: 59300,
    id: 2838419,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/james-arthur/say-you-wont-let-go/',
  },
  {
    song_Name: 'save your teas',
    reels: 52000,
    id: 3284250,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/the-weeknd/save-your-tears/',
  },

  {
    song_Name: 'Bring Me To Life',
    reels: 0000,
    id: 67344,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/evanescence/67344/',
  },
  {
    song_Name: 'Wonderwall',
    reels: 8000,
    id: 28995,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/oasis/28995/',
  },
  {
    song_Name: 'Radioactive',
    reels: 0000,
    id: 2091848,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/imagine-dragons/radioactive/',
  },
  {
    song_Name: 'Perfect',
    reels: 0000,
    id: 2882698,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ed-sheeran/perfect/',
  },
  {
    song_Name: 'Someone You Loved',
    reels: 50600,
    id: 3076787,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/lewis-capaldi/someone-you-loved/',
  },
  {
    song_Name: '7 rings',
    reels: 82200,
    id: 3089184,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ariana-grande/7-rings/',
  },
  {
    song_Name: 'Dangerous Woman',
    reels: 0000,
    id: 2792830,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/ariana-grande/dangerous-woman/',
  },
  {
    song_Name: 'The Scientist',
    reels: 14700,
    id: 64278,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/coldplay/64278/',
  },
  {
    song_Name: 'Shake It Off',
    reels: 38500,
    id: 2664415,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/taylor-swift/shake-it-off/',
  },
  {
    song_Name: 'Happy',
    reels: 1000000,
    id: 2532697,.
    problem: true,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/pharrel-williams/happy/',
  },
  {
    song_Name: 'Love Of My Life (live at wemb...)',
    reels: 347,
    id: 65113,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/queen/65113/',
  },
  {
    song_Name: 'Viva La Vida',
    reels: 0000,
    id: 1253930,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/coldplay/1253930/',
  },
  {
    song_Name: 'Shape Of You',
    reels: 131000,
    id: 2869460,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/ed-sheeran/shape-of-you/',
  },
  {
    song_Name: "Don't Let Me Down (feat. Daya)",
    reels: 18100,
    id: 2787301,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/the-chainsmokers/dont-let-me-down/',
  },
  {
    song_Name: 'The Lazy Song',
    reels: 60900,
    id: 1751595,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/bruno-mars/1751595/',
  },
  {
    song_Name: 'Hear Me Now',
    reels: 28200,
    id: 2836081,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/alok/hear-me-now/',
  },
  {
    song_Name: 'faded',
    reels: 105000,
    id: 2778053,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/alan-walker/faded/',
  },
  {
    song_Name: 'Friends',
    reels: 23900,
    id: 2977586,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/marshmello/friends-feat-anne-marie/',
  },
  {
    song_Name: 'Happier',
    reels: 19300,
    id: 3038012,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/marshmello/happier-feat-bastille/',
  },
  {
    song_Name: 'Need To Know',
    reels: 375000,
    id: 3492717,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/doja-cat/need-to-know/',
  },
  {
    song_Name: 'All I Want',
    reels: 13100,
    id: 2175837,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/kodaline/all-i-want/',
  },
  {
    song_Name: 'Let Me Love You (feat. DJ Snake)',
    reels: 86600,
    id: 2822720,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/justin-bieber/let-me-love-you/',
  },
  {
    song_Name: 'Wake Me Up (feat. Aloe Blacc)',
    reels: 28700,
    id: 2523366,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/avicii/wake-me-up-feat-aloe-blacc/',
  },
  {
    song_Name: 'The Nights',
    reels: 651000,
    id: 2672068,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/avicii/the-nights/',
  },
  {
    song_Name: 'Cure For Me',
    reels: 4514,
    id: 3503733,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/aurora/cure-for-me/',
  },
  {
    song_Name: 'Love Hurts',
    reels: 2165,
    id: 27776,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/nazareth/27776/',
  },
  {
    song_Name: 'Runaway',
    reels: 1300000,
    id: 2715550,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/aurora/runaway/',
  },
  {
    song_Name: 'Heaven',
    reels: 4407,
    id: 87,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/bryan-adams/87/',
  },
  {
    song_Name: 'When I Was Your Man',
    reels: 8716,
    id: 2200612,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/bruno-mars/when-i-was-your-man/',
  },
  {
    song_Name: 'Always Remember Us This Way',
    reels: 106000,
    id: 3052528,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/lady-gaga/always-remember-us-this-way/',
  },
  {
    song_Name: 'Love Me Like You Do',
    reels: 106000,
    id: 2698589,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/ellie-goulding/love-me-like-you-do/',
  },
  {
    song_Name: 'Rewrite The Stars (feat. Anne-Marie)',
    reels: 19900,
    id: 3079756,
    problem: true,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/james-arthur/rewrite-the-stars-feat-anne-marie/',
  },
  {
    song_Name: "i hate u, i love u (feat. Olivia O'Brien)",
    reels: 6441,
    id: 2761355,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/gnash/i-hate-you-i-love-you-ft-olivia-obrien/',
  },
  {
    song_Name: 'Love  of my life(live)',
    reels: 1385,
    id: 65113,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/queen/65113/',
  },
  {
    song_Name: 'Another Brick In The Wall Part 2',
    reels: 6610,
    id: 64541,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/pink-floyd/64541/',
  },
  {
    song_Name: "Livin' On a Prayer",
    reels: 10400,
    id: 4932,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/bon-jovi/4932/',
  },
  {
    song_Name: 'Listen To Your Heart (swedish sing',
    reels: 4085,
    id: 34460,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/roxette/34460/',
  },
  {
    song_Name: 'All I Want',
    reels: 7858,
    id: 3240567,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/olivia-rodrigo/all-i-want/',
  },
  {
    song_Name: 'Leave It All To Me (feat. Drake Bell)',
    reels: 1647,
    id: 1160806,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/miranda-cosgrove/1160806/',
  },
  {
    song_Name: 'Home',
    reels: 33400,
    id: 128318,
    emAlta: true,
    done: true,
    link: 'https://www.letras.mus.br/michael-buble/128318/traducao.html',
  },
  {
    song_Name: 'Flames',
    reels: 3029,
    id: 2990365,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/david-guetta/flames-feat-sia/',
  },
  {
    song_Name: 'Starman (2002 Remaster)',
    reels: 2868,
    id: 5355,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/david-bowie/5355/',
  },
  {
    song_Name: "I'm Just a Kid",
    reels: 51500,
    id: 76097,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/simple-plan/76097/',
  },
  {
    song_Name: 'Charlie',
    reels: 32,
    id: 535089,
    emAlta: false,
    link: 'https://www.letras.mus.br/red-hot-chili-peppers/535089/',
  },
  {
    song_Name: 'Under The Bridge',
    reels: 5204,
    id: 32739,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/red-hot-chili-peppers/32739/',
  },
  {
    song_Name: 'By The Way',
    reels: 3884,
    id: 63271,
    emAlta: false,
    link: 'https://www.letras.mus.br/red-hot-chili-peppers/32739/',
  },
  {
    song_Name: 'Otherside',
    reels: 5135,
    id: 1965384,
    emAlta: false,
    done: true,
    link: 'https://www.letras.mus.br/red-hot-chili-peppers/1965384/',
  },
  {
    song_Name: 'One',
    reels: 2545,
    id: 25926,
    emAlta: false,
    link: 'https://www.letras.mus.br/metallica/25926/',
  },
  {
    song_Name: 'Nothing Else Matters',
    reels: 7996,
    id: 25935,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/metallica/25935/',
  },
  {
    song_Name: 'Whiskey In The Jar',
    reels: 5317,
    id: 25940,
    emAlta: false,
    done: false,
    link: 'https://www.letras.mus.br/metallica/25940/',
  },

  {
    song_Name: 'Mistletoe',
    reels: 20800,
    id: 1972380,
    emAlta: true,
    done: false,
    link: 'https://www.letras.mus.br/justin-bieber/1972380/',
  },
]
const addKeys = songs => {
  return songs.map(song => {
    if (!song.done) {
      song.done = false
    }
    if (!song.problem) {
      song.problem = false
    }
    return {
      song_Name: song.song_Name,
      reels: song.reels,
      id: song.id,
      problem: song.problem,
      emAlta: song.emAlta,
      done: song.done,
      link: song.link,
    }
  })
}

module.exports = addKeys(songs)
